#!/bin/bash

set -e

printf "⏳ Loading context data "


curl -G -X GET \
  'http://localhost:1026/v2/entities/urn:ngsi-ld:Shelf:unit001' \
  -d 'type=Shelf' \
  -d 'options=keyValues'

echo -e " \033[1;32mdone\033[0m"